project:
  type: website
website:
  title: "Yiqun Yu EPPS 6356 Website"
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Assignment"
        menu:
          - text: "Assignment 1"
            href: assignment1.qmd
          - text: "Assignment 2"
            href: assignment2.qmd
            - text: "Assignment 5"
            href: assignment5.qmd
      - text: "Prepare for Class"
        menu:
          - text: "Prepare 4"
            href: pre4.qmd
    right:
      - icon: github
        href: https://github.com/yuyiqun03
  search: true

format:
  html:
    theme: "flatly"
    highlight-style: "tango"
    number-sections: false
    css: styles.css
    
editor: visual

